name: 'ClaudeChain'
description: 'Automate code refactoring with AI using Claude Code. Creates incremental PRs for systematic codebase improvements.'
author: 'gestrich'

branding:
  icon: 'git-pull-request'
  color: 'orange'

inputs:
  anthropic_api_key:
    description: 'Anthropic API key for Claude Code'
    required: true
  github_token:
    description: 'GitHub token for PR creation and API access'
    required: true
    default: ${{ github.token }}

  # Event context inputs (for simplified workflow)
  github_event:
    description: 'GitHub event payload JSON. Used for automatic event handling.'
    required: false
  event_name:
    description: 'GitHub event name. Used with github_event for automatic handling.'
    required: false

  # Project configuration
  project_name:
    description: 'Project folder name under /claude-chain directory. Required if github_event is not provided.'
    required: false
  default_base_branch:
    # Default defined in src/claudechain/domain/constants.py (DEFAULT_BASE_BRANCH)
    description: 'Default base branch if not specified in project config or event context. Defaults to main.'
    required: false
  merged_pr_number:
    description: 'PR number that was just merged (for auto-detecting project from labels)'
    required: false
  claude_model:
    description: 'Claude model to use (e.g., claude-sonnet-4-5)'
    required: false
    default: 'claude-sonnet-4-5'
  claude_allowed_tools:
    # Default defined in src/claudechain/domain/constants.py (DEFAULT_ALLOWED_TOOLS)
    description: 'Comma-separated list of tools Claude can use. Defaults to minimal permissions: Read,Write,Edit,Bash(git add:*),Bash(git commit:*)'
    required: false
  base_branch:
    # Default defined in src/claudechain/domain/constants.py (DEFAULT_BASE_BRANCH)
    description: 'Base branch where spec files must exist (fetched via GitHub API) and where pull requests will target. Defaults to main.'
    required: false
  working_directory:
    description: 'Working directory for the action'
    required: false
    default: '.'
  add_pr_summary:
    description: 'Add AI-generated summary comment to PR (true/false)'
    required: false
    default: 'true'
  slack_webhook_url:
    description: 'Slack webhook URL for PR notifications (optional)'
    required: false
    default: ''
  pr_label:
    description: 'Label to apply to ClaudeChain PRs'
    required: false
    default: 'claudechain'

outputs:
  # Execution status outputs (for simplified workflow)
  skipped:
    description: 'Whether execution was skipped (true/false). Check skip_reason for details.'
    value: ${{ steps.parse.outputs.skip }}
  skip_reason:
    description: 'Reason for skipping if skipped (e.g., "No claudechain label", "PR not merged")'
    value: ${{ steps.parse.outputs.skip_reason }}

  # Resolved configuration outputs
  project_name:
    description: 'Detected/resolved project name'
    value: ${{ steps.parse.outputs.project_name || steps.prepare.outputs.project_name }}
  base_branch:
    description: 'Resolved base branch'
    value: ${{ steps.parse.outputs.base_branch || inputs.base_branch }}

  # PR outputs
  pr_number:
    description: 'Number of created PR (empty if none created)'
    value: ${{ steps.finalize.outputs.pr_number }}
  pr_url:
    description: 'URL of created PR (empty if none created)'
    value: ${{ steps.finalize.outputs.pr_url }}

  # Assignee and task outputs
  assignee:
    description: 'Assigned GitHub username (empty if none assigned)'
    value: ${{ steps.prepare.outputs.assignee }}
  task_completed:
    description: 'Task description that was completed (empty if none)'
    value: ${{ steps.prepare.outputs.task_description }}
  has_capacity:
    description: 'Whether project has capacity for a new PR (true/false)'
    value: ${{ steps.prepare.outputs.has_capacity }}
  all_tasks_done:
    description: 'Whether all tasks are complete (true/false)'
    value: ${{ steps.prepare.outputs.all_tasks_done }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      shell: bash
      run: pip install PyYAML

    # Event parsing and checkout (simplified workflow)
    # These steps are only active when github_event is provided
    - name: Parse event and determine action
      id: parse
      if: inputs.github_event != ''
      shell: bash
      env:
        EVENT_NAME: ${{ inputs.event_name }}
        EVENT_JSON: ${{ inputs.github_event }}
        PROJECT_NAME: ${{ inputs.project_name }}
        DEFAULT_BASE_BRANCH: ${{ inputs.default_base_branch }}
        PR_LABEL: ${{ inputs.pr_label }}
        ACTION_PATH: ${{ github.action_path }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        export PYTHONPATH="$ACTION_PATH/src:$PYTHONPATH"
        python3 -m claudechain parse-event

    - name: Log skip reason
      if: inputs.github_event != '' && steps.parse.outputs.skip == 'true'
      shell: bash
      run: |
        echo "::notice::Skipping ClaudeChain: ${{ steps.parse.outputs.skip_reason }}"
        echo "## ⏭️ Skipped" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Reason:** ${{ steps.parse.outputs.skip_reason }}" >> $GITHUB_STEP_SUMMARY

    - name: Checkout repository
      if: inputs.github_event != '' && steps.parse.outputs.skip != 'true'
      uses: actions/checkout@v4
      with:
        ref: ${{ steps.parse.outputs.checkout_ref }}
        fetch-depth: 0

    - name: Prepare for Claude Code execution
      id: prepare
      if: inputs.github_event == '' || steps.parse.outputs.skip != 'true'
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        # Use parsed values when available (simplified workflow), otherwise fall back to direct inputs
        PROJECT_NAME: ${{ steps.parse.outputs.project_name || inputs.project_name }}
        MERGED_PR_NUMBER: ${{ steps.parse.outputs.merged_pr_number || inputs.merged_pr_number }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        BASE_BRANCH: ${{ steps.parse.outputs.base_branch || inputs.base_branch }}
        ACTION_PATH: ${{ github.action_path }}
        SLACK_WEBHOOK_URL: ${{ inputs.slack_webhook_url }}
        PR_LABEL: ${{ inputs.pr_label }}
        CLAUDE_ALLOWED_TOOLS: ${{ inputs.claude_allowed_tools }}
      run: |
        export PYTHONPATH="$ACTION_PATH/src:$PYTHONPATH"
        python3 -m claudechain prepare

    # WORKAROUND: Clean stale Claude Code lock files before installation
    # Issue: https://github.com/anthropics/claude-code-action/issues/709
    # When Claude Code installation times out, it leaves behind a lock file at
    # ~/.local/state/claude/locks/[version].lock that prevents retry attempts.
    # This causes "another process is currently installing Claude" errors.
    # Remove this step when the upstream issue is resolved.
    - name: Clean Claude Code lock files
      if: steps.prepare.outputs.has_capacity == 'true' && steps.prepare.outputs.has_task == 'true'
      shell: bash
      run: rm -rf ~/.local/state/claude/locks
      continue-on-error: true

    - name: Run Claude Code
      id: claude_code
      if: steps.prepare.outputs.has_capacity == 'true' && steps.prepare.outputs.has_task == 'true'
      uses: anthropics/claude-code-action@v1
      with:
        prompt: ${{ steps.prepare.outputs.claude_prompt }}
        anthropic_api_key: ${{ inputs.anthropic_api_key }}
        github_token: ${{ inputs.github_token }}
        claude_args: '--allowedTools ${{ steps.prepare.outputs.allowed_tools }} --model ${{ inputs.claude_model }}'
        show_full_output: true

    # Preserve main execution file before summary step overwrites it
    # claude-code-action uses a fixed output filename, so we copy it to a unique location
    - name: Preserve main execution file
      id: preserve_main_execution
      if: steps.claude_code.outputs.execution_file != ''
      shell: bash
      run: |
        MAIN_EXEC_FILE="${{ runner.temp }}/claude-main-execution.json"
        cp "${{ steps.claude_code.outputs.execution_file }}" "$MAIN_EXEC_FILE"
        echo "main_execution_file=$MAIN_EXEC_FILE" >> $GITHUB_OUTPUT
        echo "Preserved main execution file to: $MAIN_EXEC_FILE"

    - name: Finalize and create PR
      id: finalize
      if: always() && (inputs.github_event == '' || steps.parse.outputs.skip != 'true')
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        BRANCH_NAME: ${{ steps.prepare.outputs.branch_name }}
        LABEL: ${{ steps.prepare.outputs.label }}
        ASSIGNEE: ${{ steps.prepare.outputs.assignee }}
        TASK_DESCRIPTION: ${{ steps.prepare.outputs.task_description }}
        TASK_INDEX: ${{ steps.prepare.outputs.task_index }}
        PROJECT: ${{ steps.prepare.outputs.project_name }}
        PROJECT_PATH: ${{ steps.prepare.outputs.project_path }}
        SPEC_PATH: ${{ steps.prepare.outputs.spec_path }}
        PR_TEMPLATE_PATH: ${{ steps.prepare.outputs.pr_template_path }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_RUN_ID: ${{ github.run_id }}
        BASE_BRANCH: ${{ steps.parse.outputs.base_branch || inputs.base_branch }}
        HAS_CAPACITY: ${{ steps.prepare.outputs.has_capacity }}
        HAS_TASK: ${{ steps.prepare.outputs.has_task }}
        ACTION_PATH: ${{ github.action_path }}
      run: |
        export PYTHONPATH="$ACTION_PATH/src:$PYTHONPATH"
        python3 -m claudechain finalize

    - name: Prepare summary prompt
      id: prepare_summary
      if: |
        inputs.add_pr_summary == 'true' &&
        steps.finalize.outputs.pr_number != ''
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        PR_NUMBER: ${{ steps.finalize.outputs.pr_number }}
        TASK_DESCRIPTION: ${{ steps.prepare.outputs.task_description }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_RUN_ID: ${{ github.run_id }}
        ACTION_PATH: ${{ github.action_path }}
      run: |
        export PYTHONPATH="$ACTION_PATH/src:$PYTHONPATH"
        python3 -m claudechain prepare-summary

    - name: Generate PR summary
      id: pr_summary
      if: |
        inputs.add_pr_summary == 'true' &&
        steps.prepare_summary.outputs.summary_prompt != ''
      uses: anthropics/claude-code-action@v1
      with:
        prompt: ${{ steps.prepare_summary.outputs.summary_prompt }}
        anthropic_api_key: ${{ inputs.anthropic_api_key }}
        github_token: ${{ inputs.github_token }}
        claude_args: '--allowedTools "Bash(gh pr diff:*),Bash(cat:*),Write" --model ${{ inputs.claude_model }}'
        show_full_output: true

    # Preserve summary execution file for consistent cost tracking
    - name: Preserve summary execution file
      id: preserve_summary_execution
      if: steps.pr_summary.outputs.execution_file != ''
      shell: bash
      run: |
        SUMMARY_EXEC_FILE="${{ runner.temp }}/claude-summary-execution.json"
        cp "${{ steps.pr_summary.outputs.execution_file }}" "$SUMMARY_EXEC_FILE"
        echo "summary_execution_file=$SUMMARY_EXEC_FILE" >> $GITHUB_OUTPUT
        echo "Preserved summary execution file to: $SUMMARY_EXEC_FILE"

    - name: Post PR summary and cost
      id: post_pr_comment
      if: steps.finalize.outputs.pr_number != ''
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        PR_NUMBER: ${{ steps.finalize.outputs.pr_number }}
        SUMMARY_FILE: ${{ steps.prepare_summary.outputs.summary_file }}
        # Use preserved execution files for accurate cost tracking
        MAIN_EXECUTION_FILE: ${{ steps.preserve_main_execution.outputs.main_execution_file || steps.claude_code.outputs.execution_file }}
        SUMMARY_EXECUTION_FILE: ${{ steps.preserve_summary_execution.outputs.summary_execution_file || steps.pr_summary.outputs.execution_file }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_RUN_ID: ${{ github.run_id }}
        ACTION_PATH: ${{ github.action_path }}
        TASK_DESCRIPTION: ${{ steps.prepare.outputs.task_description }}
      run: |
        export PYTHONPATH="$ACTION_PATH/src:$PYTHONPATH"
        python3 -m claudechain post-pr-comment
      continue-on-error: true

    - name: Format Slack notification
      id: notify
      if: steps.finalize.outputs.pr_number != ''
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        PR_NUMBER: ${{ steps.finalize.outputs.pr_number }}
        PR_URL: ${{ steps.finalize.outputs.pr_url }}
        PROJECT_NAME: ${{ steps.prepare.outputs.project_name }}
        TASK_DESCRIPTION: ${{ steps.prepare.outputs.task_description }}
        COST_BREAKDOWN: ${{ steps.post_pr_comment.outputs.cost_breakdown }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        ACTION_PATH: ${{ github.action_path }}
      run: |
        export PYTHONPATH="$ACTION_PATH/src:$PYTHONPATH"
        python3 -m claudechain format-slack-notification
      continue-on-error: true

    - name: Post to Slack
      if: steps.notify.outputs.has_pr == 'true' && steps.prepare.outputs.slack_webhook_url != ''
      uses: slackapi/slack-github-action@v2
      with:
        webhook: ${{ steps.prepare.outputs.slack_webhook_url }}
        webhook-type: incoming-webhook
        payload: |
          {
            "text": "New ClaudeChain PR Created",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ${{ toJSON(steps.notify.outputs.slack_message) }}
                }
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": "Generated by <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|ClaudeChain>"
                  }
                ]
              }
            ]
          }

    - name: Create task metadata artifact
      id: create_artifact
      if: steps.finalize.outputs.pr_number != ''
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        COST_BREAKDOWN: ${{ steps.post_pr_comment.outputs.cost_breakdown }}
        PR_NUMBER: ${{ steps.finalize.outputs.pr_number }}
        TASK_DESCRIPTION: ${{ steps.prepare.outputs.task_description }}
        TASK_INDEX: ${{ steps.prepare.outputs.task_index }}
        TASK_HASH: ${{ steps.prepare.outputs.task_hash }}
        PROJECT: ${{ steps.prepare.outputs.project_name }}
        BRANCH_NAME: ${{ steps.prepare.outputs.branch_name }}
        ASSIGNEE: ${{ steps.prepare.outputs.assignee }}
        GITHUB_RUN_ID: ${{ github.run_id }}
        ACTION_PATH: ${{ github.action_path }}
      run: |
        export PYTHONPATH="$ACTION_PATH/src:$PYTHONPATH"
        python3 -m claudechain create-artifact
      continue-on-error: true

    - name: Upload task metadata artifact
      if: steps.create_artifact.outputs.artifact_path != ''
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.create_artifact.outputs.artifact_name }}
        path: ${{ steps.create_artifact.outputs.artifact_path }}
        retention-days: 90
        if-no-files-found: warn
