name: 'ClaudeStep'
description: 'Automate code refactoring with AI using Claude Code. Creates incremental PRs for systematic codebase improvements.'
author: 'gestrich'

branding:
  icon: 'git-pull-request'
  color: 'orange'

inputs:
  anthropic_api_key:
    description: 'Anthropic API key for Claude Code'
    required: true
  github_token:
    description: 'GitHub token for PR creation and API access'
    required: true
    default: ${{ github.token }}
  project_name:
    description: 'Project folder name under /refactor directory'
    required: false
  merged_pr_number:
    description: 'PR number that was just merged (for auto-detecting project from labels)'
    required: false
  config_path:
    description: 'Path to configuration.json file (overrides default)'
    required: false
  spec_path:
    description: 'Path to spec.md file (overrides default)'
    required: false
  pr_template_path:
    description: 'Path to pr-template.md file (overrides default)'
    required: false
  claude_model:
    description: 'Claude model to use (e.g., claude-sonnet-4-5)'
    required: false
    default: 'claude-sonnet-4-5'
  claude_allowed_tools:
    description: 'Comma-separated list of tools Claude can use'
    required: false
    default: 'Write,Read,Bash,Edit'
  base_branch:
    description: 'Base branch for pull requests'
    required: false
    default: 'main'
  working_directory:
    description: 'Working directory for the action'
    required: false
    default: '.'

outputs:
  pr_number:
    description: 'Number of created PR (empty if none created)'
    value: ${{ steps.finalize.outputs.pr_number }}
  pr_url:
    description: 'URL of created PR (empty if none created)'
    value: ${{ steps.finalize.outputs.pr_url }}
  reviewer:
    description: 'Assigned reviewer username (empty if none assigned)'
    value: ${{ steps.prepare.outputs.reviewer }}
  task_completed:
    description: 'Task description that was completed (empty if none)'
    value: ${{ steps.prepare.outputs.task }}
  has_capacity:
    description: 'Whether a reviewer had capacity (true/false)'
    value: ${{ steps.prepare.outputs.has_capacity }}
  all_tasks_done:
    description: 'Whether all tasks are complete (true/false)'
    value: ${{ steps.prepare.outputs.all_tasks_done }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Prepare for Claude Code execution
      id: prepare
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        PROJECT_NAME: ${{ inputs.project_name }}
        MERGED_PR_NUMBER: ${{ inputs.merged_pr_number }}
        CONFIG_PATH: ${{ inputs.config_path }}
        SPEC_PATH: ${{ inputs.spec_path }}
        PR_TEMPLATE_PATH: ${{ inputs.pr_template_path }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        ACTION_PATH: ${{ github.action_path }}
      run: python3 "$ACTION_PATH/scripts/refactor_chain.py" prepare

    - name: Run Claude Code
      if: steps.prepare.outputs.has_capacity == 'true' && steps.prepare.outputs.has_task == 'true'
      uses: anthropics/claude-code-action@v1
      with:
        prompt: ${{ steps.prepare.outputs.claude_prompt }}
        anthropic_api_key: ${{ inputs.anthropic_api_key }}
        github_token: ${{ inputs.github_token }}
        claude_args: '--allowedTools ${{ inputs.claude_allowed_tools }}'
        show_full_output: true

    - name: Finalize and create PR
      id: finalize
      if: always()
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        BRANCH_NAME: ${{ steps.prepare.outputs.branch_name }}
        LABEL: ${{ steps.prepare.outputs.label }}
        REVIEWER: ${{ steps.prepare.outputs.reviewer }}
        TASK: ${{ steps.prepare.outputs.task }}
        TASK_INDEX: ${{ steps.prepare.outputs.task_index }}
        PROJECT: ${{ steps.prepare.outputs.project_name }}
        PROJECT_PATH: ${{ steps.prepare.outputs.project_path }}
        SPEC_PATH: ${{ steps.prepare.outputs.spec_path }}
        PR_TEMPLATE_PATH: ${{ steps.prepare.outputs.pr_template_path }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_RUN_ID: ${{ github.run_id }}
        BASE_BRANCH: ${{ inputs.base_branch }}
        HAS_CAPACITY: ${{ steps.prepare.outputs.has_capacity }}
        HAS_TASK: ${{ steps.prepare.outputs.has_task }}
        ACTION_PATH: ${{ github.action_path }}
      run: python3 "$ACTION_PATH/scripts/refactor_chain.py" finalize

    - name: Upload task metadata artifact
      if: steps.finalize.outputs.artifact_path != ''
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.finalize.outputs.artifact_name }}
        path: ${{ steps.finalize.outputs.artifact_path }}
        retention-days: 90
        if-no-files-found: warn
