name: 'ClaudeStep'
description: 'Automate code refactoring with AI using Claude Code. Creates incremental PRs for systematic codebase improvements.'
author: 'gestrich'

branding:
  icon: 'git-pull-request'
  color: 'orange'

inputs:
  anthropic_api_key:
    description: 'Anthropic API key for Claude Code'
    required: true
  github_token:
    description: 'GitHub token for PR creation and API access'
    required: true
    default: ${{ github.token }}
  project_name:
    description: 'Project folder name under /claude-step directory'
    required: true
  merged_pr_number:
    description: 'PR number that was just merged (for auto-detecting project from labels)'
    required: false
  claude_model:
    description: 'Claude model to use (e.g., claude-sonnet-4-5)'
    required: false
    default: 'claude-sonnet-4-5'
  claude_allowed_tools:
    description: 'Comma-separated list of tools Claude can use'
    required: false
    default: 'Write,Read,Bash,Edit'
  base_branch:
    description: 'Base branch for pull requests'
    required: false
    default: 'main'
  working_directory:
    description: 'Working directory for the action'
    required: false
    default: '.'
  add_pr_summary:
    description: 'Add AI-generated summary comment to PR (true/false)'
    required: false
    default: 'true'
  slack_webhook_url:
    description: 'Slack webhook URL for PR notifications (optional)'
    required: false
    default: ''
  pr_label:
    description: 'Label to apply to ClaudeStep PRs'
    required: false
    default: 'claudestep'

outputs:
  pr_number:
    description: 'Number of created PR (empty if none created)'
    value: ${{ steps.finalize.outputs.pr_number }}
  pr_url:
    description: 'URL of created PR (empty if none created)'
    value: ${{ steps.finalize.outputs.pr_url }}
  reviewer:
    description: 'Assigned reviewer username (empty if none assigned)'
    value: ${{ steps.prepare.outputs.reviewer }}
  task_completed:
    description: 'Task description that was completed (empty if none)'
    value: ${{ steps.prepare.outputs.task }}
  has_capacity:
    description: 'Whether a reviewer had capacity (true/false)'
    value: ${{ steps.prepare.outputs.has_capacity }}
  all_tasks_done:
    description: 'Whether all tasks are complete (true/false)'
    value: ${{ steps.prepare.outputs.all_tasks_done }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      shell: bash
      run: pip install PyYAML

    - name: Prepare for Claude Code execution
      id: prepare
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        PROJECT_NAME: ${{ inputs.project_name }}
        MERGED_PR_NUMBER: ${{ inputs.merged_pr_number }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        ACTION_PATH: ${{ github.action_path }}
        SLACK_WEBHOOK_URL: ${{ inputs.slack_webhook_url }}
        PR_LABEL: ${{ inputs.pr_label }}
      run: |
        export PYTHONPATH="$ACTION_PATH/src:$PYTHONPATH"
        python3 -m claudestep prepare

    # WORKAROUND: Clean stale Claude Code lock files before installation
    # Issue: https://github.com/anthropics/claude-code-action/issues/709
    # When Claude Code installation times out, it leaves behind a lock file at
    # ~/.local/state/claude/locks/[version].lock that prevents retry attempts.
    # This causes "another process is currently installing Claude" errors.
    # Remove this step when the upstream issue is resolved.
    - name: Clean Claude Code lock files
      if: steps.prepare.outputs.has_capacity == 'true' && steps.prepare.outputs.has_task == 'true'
      shell: bash
      run: rm -rf ~/.local/state/claude/locks
      continue-on-error: true

    - name: Run Claude Code
      id: claude_code
      if: steps.prepare.outputs.has_capacity == 'true' && steps.prepare.outputs.has_task == 'true'
      uses: anthropics/claude-code-action@v1
      with:
        prompt: ${{ steps.prepare.outputs.claude_prompt }}
        anthropic_api_key: ${{ inputs.anthropic_api_key }}
        github_token: ${{ inputs.github_token }}
        claude_args: '--allowedTools ${{ inputs.claude_allowed_tools }}'
        show_full_output: true

    - name: Extract cost from main task
      id: extract_main_cost
      if: steps.claude_code.outputs.execution_file != ''
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        EXECUTION_FILE: ${{ steps.claude_code.outputs.execution_file }}
        EXECUTION_INDEX: '-1'  # Last item (only main task execution at this point)
        ACTION_PATH: ${{ github.action_path }}
      run: |
        export PYTHONPATH="$ACTION_PATH/src:$PYTHONPATH"
        python3 -m claudestep extract-cost
      continue-on-error: true

    - name: Finalize and create PR
      id: finalize
      if: always()
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        BRANCH_NAME: ${{ steps.prepare.outputs.branch_name }}
        LABEL: ${{ steps.prepare.outputs.label }}
        REVIEWER: ${{ steps.prepare.outputs.reviewer }}
        TASK: ${{ steps.prepare.outputs.task }}
        TASK_INDEX: ${{ steps.prepare.outputs.task_index }}
        PROJECT: ${{ steps.prepare.outputs.project_name }}
        PROJECT_PATH: ${{ steps.prepare.outputs.project_path }}
        SPEC_PATH: ${{ steps.prepare.outputs.spec_path }}
        PR_TEMPLATE_PATH: ${{ steps.prepare.outputs.pr_template_path }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_RUN_ID: ${{ github.run_id }}
        BASE_BRANCH: ${{ inputs.base_branch }}
        HAS_CAPACITY: ${{ steps.prepare.outputs.has_capacity }}
        HAS_TASK: ${{ steps.prepare.outputs.has_task }}
        ACTION_PATH: ${{ github.action_path }}
      run: |
        export PYTHONPATH="$ACTION_PATH/src:$PYTHONPATH"
        python3 -m claudestep finalize

    - name: Prepare summary prompt
      id: prepare_summary
      if: |
        inputs.add_pr_summary == 'true' &&
        steps.finalize.outputs.pr_number != ''
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        PR_NUMBER: ${{ steps.finalize.outputs.pr_number }}
        TASK: ${{ steps.prepare.outputs.task }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_RUN_ID: ${{ github.run_id }}
        ACTION_PATH: ${{ github.action_path }}
      run: |
        export PYTHONPATH="$ACTION_PATH/src:$PYTHONPATH"
        python3 -m claudestep prepare-summary

    - name: Generate and post PR summary
      id: pr_summary
      if: |
        inputs.add_pr_summary == 'true' &&
        steps.prepare_summary.outputs.summary_prompt != ''
      uses: anthropics/claude-code-action@v1
      with:
        prompt: ${{ steps.prepare_summary.outputs.summary_prompt }}
        anthropic_api_key: ${{ inputs.anthropic_api_key }}
        github_token: ${{ inputs.github_token }}
        claude_args: '--allowedTools Bash'
        show_full_output: true
      continue-on-error: true

    - name: Extract cost from PR summary
      id: extract_summary_cost
      if: |
        inputs.add_pr_summary == 'true' &&
        steps.finalize.outputs.pr_number != '' &&
        steps.pr_summary.outputs.execution_file != ''
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        EXECUTION_FILE: ${{ steps.pr_summary.outputs.execution_file }}
        EXECUTION_INDEX: '-1'  # Last item (PR summary)
        ACTION_PATH: ${{ github.action_path }}
      run: |
        export PYTHONPATH="$ACTION_PATH/src:$PYTHONPATH"
        python3 -m claudestep extract-cost
      continue-on-error: true

    - name: Post cost breakdown to PR
      if: steps.finalize.outputs.pr_number != ''
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        PR_NUMBER: ${{ steps.finalize.outputs.pr_number }}
        MAIN_COST: ${{ steps.extract_main_cost.outputs.cost_usd }}
        SUMMARY_COST: ${{ steps.extract_summary_cost.outputs.cost_usd }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_RUN_ID: ${{ github.run_id }}
        ACTION_PATH: ${{ github.action_path }}
      run: |
        export PYTHONPATH="$ACTION_PATH/src:$PYTHONPATH"
        python3 -m claudestep add-cost-comment
      continue-on-error: true

    - name: Prepare Slack notification
      id: notify
      if: steps.finalize.outputs.pr_number != ''
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        PR_NUMBER: ${{ steps.finalize.outputs.pr_number }}
        PR_URL: ${{ steps.finalize.outputs.pr_url }}
        PROJECT_NAME: ${{ steps.prepare.outputs.project_name }}
        TASK: ${{ steps.prepare.outputs.task }}
        MAIN_COST: ${{ steps.extract_main_cost.outputs.cost_usd }}
        SUMMARY_COST: ${{ steps.extract_summary_cost.outputs.cost_usd }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        ACTION_PATH: ${{ github.action_path }}
      run: |
        export PYTHONPATH="$ACTION_PATH/src:$PYTHONPATH"
        python3 -m claudestep notify-pr
      continue-on-error: true

    - name: Check Slack configuration
      if: steps.finalize.outputs.pr_number != ''
      shell: bash
      run: |
        echo "=== Slack Notification Status ==="
        echo "has_pr: ${{ steps.notify.outputs.has_pr }}"
        echo "slack_webhook_url configured: ${{ steps.prepare.outputs.slack_webhook_url != '' }}"
        if [ "${{ steps.prepare.outputs.slack_webhook_url }}" = "" ]; then
          echo "⚠️  Slack webhook URL not configured - notifications will be skipped"
          echo "To enable Slack notifications, add 'slack_webhook_url' input to your workflow"
        else
          echo "✓ Slack webhook URL is configured - notification will be posted"
        fi

    - name: Post to Slack
      if: steps.notify.outputs.has_pr == 'true' && steps.prepare.outputs.slack_webhook_url != ''
      uses: slackapi/slack-github-action@v2
      with:
        webhook: ${{ steps.prepare.outputs.slack_webhook_url }}
        webhook-type: incoming-webhook
        payload: |
          {
            "text": "New ClaudeStep PR Created",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ${{ toJSON(steps.notify.outputs.slack_message) }}
                }
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": "Generated by <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|ClaudeStep>"
                  }
                ]
              }
            ]
          }
      continue-on-error: true

    - name: Upload task metadata artifact
      if: steps.finalize.outputs.artifact_path != ''
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.finalize.outputs.artifact_name }}
        path: ${{ steps.finalize.outputs.artifact_path }}
        retention-days: 90
        if-no-files-found: warn
