name: 'ClaudeStep Discovery'
description: 'Discover all refactor projects that have reviewer capacity and available tasks. Returns list of projects to process.'
author: 'gestrich'

branding:
  icon: 'search'
  color: 'orange'

inputs:
  github_token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}
  working_directory:
    description: 'Working directory for the action'
    required: false
    default: '.'

outputs:
  projects:
    description: 'JSON array of project names that have capacity and tasks'
    value: ${{ steps.discover.outputs.projects }}
  project_count:
    description: 'Number of projects that have work to do'
    value: ${{ steps.discover.outputs.project_count }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Discover projects with work
      id: discover
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        ACTION_PATH: ${{ github.action_path }}/../
      run: |
        export PYTHONPATH="$ACTION_PATH/src:$PYTHONPATH"
        python3 -m claudestep discover-ready
