name: 'ClaudeStep Discovery'
description: 'Discover all refactor projects that have reviewer capacity and available tasks. Returns list of projects to process.'
author: 'gestrich'

branding:
  icon: 'search'
  color: 'orange'

inputs:
  github_token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}
  working_directory:
    description: 'Working directory for the action'
    required: false
    default: '.'

outputs:
  projects:
    description: 'JSON array of project names that have capacity and tasks'
    value: ${{ steps.discover.outputs.projects }}
  project_count:
    description: 'Number of projects that have work to do'
    value: ${{ steps.discover.outputs.project_count }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Discover projects with work
      id: discover
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        ACTION_PATH: ${{ github.action_path }}/../
      run: |
        export PYTHONPATH="$ACTION_PATH/scripts:$PYTHONPATH"

        echo "========================================================================"
        echo "ClaudeStep Discovery Mode"
        echo "========================================================================"
        echo ""
        echo "ðŸ” Finding all projects with capacity and available tasks..."
        echo ""

        # Discover all projects
        ALL_PROJECTS_JSON=$(python3 -m claudestep discover 2>&1 | grep "^projects=" | cut -d'=' -f2)

        if [ -z "$ALL_PROJECTS_JSON" ] || [ "$ALL_PROJECTS_JSON" = "[]" ]; then
            echo "No refactor projects found"
            echo "projects=[]" >> $GITHUB_OUTPUT
            echo "project_count=0" >> $GITHUB_OUTPUT
            exit 0
        fi

        # Check each project for capacity and tasks
        READY_PROJECTS=()

        readarray -t ALL_PROJECTS < <(echo "$ALL_PROJECTS_JSON" | jq -r '.[]')

        for PROJECT in "${ALL_PROJECTS[@]}"; do
            echo "Checking project: $PROJECT"

            # Check if project has config
            if [ ! -f "refactor/$PROJECT/configuration.json" ]; then
                echo "  â­ï¸  No configuration.json found"
                continue
            fi

            # Check if project has spec
            if [ ! -f "refactor/$PROJECT/spec.md" ]; then
                echo "  â­ï¸  No spec.md found"
                continue
            fi

            # Load config and check for reviewers
            REVIEWERS=$(jq -r '.reviewers // [] | length' "refactor/$PROJECT/configuration.json")
            if [ "$REVIEWERS" = "0" ]; then
                echo "  â­ï¸  No reviewers configured"
                continue
            fi

            # Check for uncompleted tasks in spec.md
            UNCOMPLETED_TASKS=$(grep -c '^\s*- \[ \]' "refactor/$PROJECT/spec.md" || echo "0")
            if [ "$UNCOMPLETED_TASKS" = "0" ]; then
                echo "  â­ï¸  No uncompleted tasks"
                continue
            fi

            # Check reviewer capacity (count open PRs for this project)
            OPEN_PRS=$(gh pr list --repo "$GITHUB_REPOSITORY" --label "claudestep" --state open --json title --jq "map(select(.title | contains(\"[$PROJECT]\")))" | jq '. | length')

            # Get max concurrent PRs (sum of all reviewer maxOpenPRs)
            MAX_PRS=$(jq -r '[.reviewers[].maxOpenPRs] | add' "refactor/$PROJECT/configuration.json")

            if [ "$OPEN_PRS" -ge "$MAX_PRS" ]; then
                echo "  â­ï¸  At capacity ($OPEN_PRS/$MAX_PRS PRs open)"
                continue
            fi

            echo "  âœ… Ready for work ($OPEN_PRS/$MAX_PRS PRs, $UNCOMPLETED_TASKS tasks remaining)"
            READY_PROJECTS+=("$PROJECT")
        done

        # Convert to JSON array
        if [ ${#READY_PROJECTS[@]} -eq 0 ]; then
            echo ""
            echo "No projects have available capacity and tasks"
            echo "projects=[]" >> $GITHUB_OUTPUT
            echo "project_count=0" >> $GITHUB_OUTPUT
        else
            READY_JSON=$(printf '%s\n' "${READY_PROJECTS[@]}" | jq -R . | jq -s .)
            echo ""
            echo "========================================================================"
            echo "Found ${#READY_PROJECTS[@]} project(s) ready for work:"
            printf '  - %s\n' "${READY_PROJECTS[@]}"
            echo "========================================================================"
            echo ""
            echo "projects=$READY_JSON" >> $GITHUB_OUTPUT
            echo "project_count=${#READY_PROJECTS[@]}" >> $GITHUB_OUTPUT
        fi
