name: 'ClaudeChain Statistics'
description: 'Generate statistics and reports for ClaudeChain projects'
author: 'gestrich'

branding:
  icon: 'bar-chart-2'
  color: 'blue'

inputs:
  github_token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}
  base_branch:
    description: 'Base branch where spec files are located (fetched via GitHub API for statistics collection)'
    required: false
    default: 'main'
  config_path:
    description: 'Path to configuration.json (for single project stats)'
    required: false
  days_back:
    description: 'Days to look back for team member statistics'
    required: false
    default: '30'
  working_directory:
    description: 'Working directory for the action'
    required: false
    default: '.'
  slack_webhook_url:
    description: 'Slack webhook URL for statistics notifications (optional)'
    required: false
    default: ''
  show_reviewer_stats:
    description: 'Show reviewer leaderboard statistics (default: false)'
    required: false
    default: 'false'

outputs:
  slack_message:
    description: 'Formatted message for Slack (mrkdwn format)'
    value: ${{ steps.stats.outputs.slack_message }}
  statistics_json:
    description: 'JSON statistics data'
    value: ${{ steps.stats.outputs.statistics_json }}
  has_statistics:
    description: 'Whether statistics were generated (true/false)'
    value: ${{ steps.stats.outputs.has_statistics }}
  slack_webhook_url:
    description: 'Slack webhook URL (passed through from input)'
    value: ${{ steps.stats.outputs.slack_webhook_url }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      shell: bash
      run: pip install PyYAML

    - name: Generate statistics
      id: stats
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        BASE_BRANCH: ${{ inputs.base_branch }}
        CONFIG_PATH: ${{ inputs.config_path }}
        STATS_DAYS_BACK: ${{ inputs.days_back }}
        STATS_FORMAT: 'slack'
        ACTION_PATH: ${{ github.action_path }}
        SLACK_WEBHOOK_URL: ${{ inputs.slack_webhook_url }}
        SHOW_REVIEWER_STATS: ${{ inputs.show_reviewer_stats }}
        GITHUB_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      run: |
        # ACTION_PATH points to statistics/ subdir, need parent for src/
        ACTION_ROOT=$(dirname "$ACTION_PATH")
        export PYTHONPATH="$ACTION_ROOT/src:$PYTHONPATH"
        python3 -m claudechain statistics

    - name: Post to Slack
      if: steps.stats.outputs.has_statistics == 'true' && steps.stats.outputs.slack_webhook_url != ''
      uses: slackapi/slack-github-action@v2
      continue-on-error: true
      with:
        webhook: ${{ steps.stats.outputs.slack_webhook_url }}
        webhook-type: incoming-webhook
        payload: ${{ steps.stats.outputs.slack_message }}
