# Advanced Example: Multi-Trigger with Custom Configuration
#
# This workflow demonstrates:
# - Multiple trigger modes (scheduled, manual, automatic on PR merge)
# - Dynamic project detection from PR branch names
# - Custom Claude model and tool configuration
# - Output usage for downstream jobs

name: ClaudeStep

on:
  # Scheduled: Run daily at 9 AM UTC
  schedule:
    - cron: '0 9 * * *'

  # Manual: Allow triggering with project selection
  workflow_dispatch:
    inputs:
      project:
        description: 'Project name'
        required: true
        type: choice
        options:
          - swift-migration
          - typescript-conversion
          - api-refactor

  # Automatic: Trigger on PR close (merged or not) to create the next PR
  # Note: If closing without merging, update spec.md first to avoid the PR re-opening
  pull_request:
    types: [closed]

permissions:
  contents: write
  pull-requests: write
  actions: read

jobs:
  refactor:
    runs-on: ubuntu-latest

    outputs:
      pr_created: ${{ steps.refactor.outputs.pr_number != '' }}
      pr_url: ${{ steps.refactor.outputs.pr_url }}

    steps:
      - uses: actions/checkout@v4

      - name: Determine project
        id: project
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            # Use manual input
            PROJECT="${{ github.event.inputs.project }}"
          elif [ "${{ github.event_name }}" = "pull_request" ]; then
            # Extract from branch name: claude-step-{project}-{index}
            BRANCH="${{ github.head_ref }}"
            PROJECT=$(echo "$BRANCH" | sed -E 's/^claude-step-([^-]+)-[0-9]+$/\1/')
          else
            # Default for scheduled runs
            PROJECT="swift-migration"
          fi
          echo "name=$PROJECT" >> $GITHUB_OUTPUT
          echo "Determined project: $PROJECT"

      - name: Run ClaudeStep
        id: refactor
        uses: ./  # Change to: gestrich/claude-step@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          project_name: ${{ steps.project.outputs.name }}
          claude_model: claude-sonnet-4-5
          claude_allowed_tools: Write,Read,Bash,Edit,Glob,Grep

      - name: Output summary
        if: steps.refactor.outputs.pr_number
        run: |
          echo "✅ **PR Created**" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **URL**: ${{ steps.refactor.outputs.pr_url }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Reviewer**: @${{ steps.refactor.outputs.reviewer }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Task**: ${{ steps.refactor.outputs.task_completed }}" >> $GITHUB_STEP_SUMMARY

  # Optional: Notify team (example)
  notify:
    needs: refactor
    if: needs.refactor.outputs.pr_created == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Send notification
        run: |
          echo "New refactor PR created: ${{ needs.refactor.outputs.pr_url }}"
          # Add Slack/Discord/Email notification here
